on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - run: echo "action_state=yellow" >> $GITHUB_ENV
    - run: echo "action_state=red" >> $GITHUB_ENV
    - run: echo "action_state is $action_state"
